version: '2'
services:
  to-do-app:
    container_name: to-do-app
    image: saharhagbi/to-do-app:to-do-app_image
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80